<a href="https://colab.research.google.com/github/haliliceylan/tinder-proxy/blob/master/Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Mining Final Project**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
# Upload csv file to the colab 
from google.colab import files 
uploaded = files.upload() sadasdasds

Saving Challenger_Ranked_Games.csv to Challenger_Ranked_Games.csv
Saving GrandMaster_Ranked_Games.csv to GrandMaster_Ranked_Games.csv
Saving Master_Ranked_Games.csv to Master_Ranked_Games.csv

In [ ]:
# Read csv file
datacsv = pd.read_csv("Challenger_Ranked_Games.csv")
#datacsv
datacsv.head()
#datacsv.tail()

       gameId  gameDuraton  ...  redTotalHeal  redObjectDamageDealt
0  4247263043         1323  ...         38711                 60463
1  4247155821         1317  ...         24829                 14105
2  4243963257          932  ...         12589                 45201
3  4241678498         2098  ...         65312                 88202
4  4241538868         2344  ...         86431                 64141

[5 rows x 50 columns]

In [ ]:
y = datacsv.temp
X = datacsv.drop('temp', axis=1)

AttributeError: ignored